version: "3.3"

services:
  redis:
    image: my_redis

  go-app:
    image: go-app
    ports:
    -   8089:8089
    links:
    -   redis

  nginx:
    image: my_nginx
    ports:
    -   80:80
    links:
    -   go-app